# Generated by Django 5.2.8 on 2025-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CRYPTO", "Crypto"),
                            ("STOCKS", "Stocks"),
                            ("FOREX", "Forex"),
                            ("DERIVATIVES", "Derivatives"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=18)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=7,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "screenshot",
                    models.ImageField(blank=True, null=True, upload_to="screenshots/"),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
    ]
